In [1]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv("student_scores.csv")
data

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85

In [6]:
x=data["Hours"]
x

0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
Name: Hours, dtype: float64

In [7]:
y=data["Scores"]
y

0     21
1     47
2     27
3     75
4     30
5     20
6     88
7     60
8     81
9     25
10    85
Name: Scores, dtype: int64

In [8]:
coffecient=np.corrcoef(x,y)

In [9]:
print(coffecient)

[[1.         0.98107134]
 [0.98107134 1.        ]]

In [11]:
r=coffecient[0,1]
print("corelational cofficient is:",r)

corelational cofficient is: 0.981071339819237